### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by freddewitt** [YunoHost-Apps/focalboard_ynh#16]
Bonjour, j'utilise Yunohost sur un raspberry pi 4 / Arm V8

L'installation semble bien se dérouler, mais une fois "terminé", j'obtiens une erreur bad gateway (err 502) lorsque je vais sur l'adresse dédiés

Voici le log : https://paste.yunohost.org/raw/akojiroxuc

Merci!

**Comment by HappyClem** [comment]
Bonjour,
Y'a-t'il des nouvelles sur le problème ?
J'ai une installation fresh de yunohost et le problème persiste (502 bad gateway juste après l'installation)

**Comment by ericgaspar** [comment]
Focalboard package is only available for amd64 architecture...

**Comment by jbastruz** [comment]
bonjour à tous, 

j'ai fait une installation cette semaine de yunohost et j'ai le même problème qu'énoncé au dessus (j'ai un Raspi 3 pour ma part)

Quelqu'un aurait des infos sur l'avancée des travaux sur le portage de focalboard sur l'architecture ARM ? @tituspijean parlait d'une tentative, a-t-elle été fructueuse ?

**Comment by tituspijean** [comment]
Hélas, non.
