### ISSUE TITLE
Things noticed after post-installation (need clarification)

### ISSUE THREAD

**Issue by nqb** [YunoHost-Apps/focalboard_ynh#52]
### Describe the bug

Hello,
I did a fresh installation using 7.5.2~ynh1 on YunoHost 11.0.10.2 with private boards only.

Things I noticed:
- it's necessary to create a dedicated domain in order to install this application
- SSO doesn't work
- You need to create manually users
- It doesn't seem to have an admin user of the installation

I open that issue to be sure that is the expected behavior.

**Comment by ericgaspar** [comment]
These are mainly upstream limitations.
