### ISSUE TITLE
Login and Registration does not work | 401 Unauthorized

### ISSUE THREAD

**Issue by lenowac** [YunoHost-Apps/focalboard_ynh#6]
may be an upstream issue, but since its probably caused by some stupid thing I did during the install or weird incompatibility ill post here.

**Logging & Registering in does not work!**
I get lots of "401 Unauthorizd" in my network logs.

IDK if that's the right place to ask and do not expect anyone to provide support just because they put code on GitHub, although some help would be sweet ^^

### Steps to reproduce

```sh
admin@host:~$ sudo yunohost app install https://github.com/YunoHost-Apps/focalboard_ynh -l Focalboard -a "domain=focalboard.domain.tld"
```

I did change the domain and not did make any line breaks.

<details><summary>Logs and Context</summary>

### Logs

```
DANGER! This app is known to be still experimental (if not explicitly not working)! 
You should probably NOT install it unless you know what you are doing. 
NO SUPPORT will be provided if this app doesn't work or breaks your system… 
If you are willing to take that risk anyway, type 'Yes, I understand': Yes, I understand

Should this app be exposed to anonymous visitors? [yes | no] (default: yes): no

Info: Installing focalboard...
Info: [....................] > Validating installation parameters...
Info: [+++.................] > Storing installation settings...
Info: [###.................] > Finding an available port...
Info: [###+................] > Installing dependencies...
Info: [####+++++...........] > Configuring system user...
Info: [#########+..........] > Creating a PostgreSQL database...
Info: [##########++........] > Setting up source files...
Info: [############+.......] > Configuring NGINX web server...
Info: [#############++.....] > Configuring a systemd service...
Info: [###############++...] > Integrating service in YunoHost...
Info: [#################...] > Starting a systemd service...
Info: [#################+..] > Configuring permissions...
Info: [##################+.] > Reloading NGINX web server...
Info: [####################] > Installation of focalboard completed
Success! Installation completed
```

***note on the unauthorized access:*** *after installation I explicitly allowed visitors through ynh/admin*

<img width="1107" alt="focalboard login log" src="https://user-images.githubusercontent.com/73599243/120988575-fbd85e80-c77e-11eb-9c8e-e9f966352b47.png">

...and you'll find the full Firefox network log (incl. full requests and responses) attached:
[focalboard.domain.tld_Archive [21-06-06 07-39-39].har.txt](https://github.com/YunoHost-Apps/focalboard_ynh/files/6607436/focalboard.domain.tld_Archive.21-06-06.07-39-39.har.txt)

### Context 

- Hardware: VPS bought online
- YunoHost version: 4.2.5.3
- I have access to my server: Through SSH | through the webadmin
- I did not mess with any focalboard or ynh core configs

</details>

**Comment by lenowac** [comment]
same problem with the debug install

```sh
sudo yunohost app install https://github.com/YunoHost-Apps/focalboard_ynh/tree/testing --debug -l Focalboard -a "domain=focalboard.domain.tld"
```

**Comment by TROMsite** [comment]
It worked for me to make a first account, but not to create a new one. I get "Invalid registration link, please contact your administrator". Maybe it is related to this https://github.com/mattermost/focalboard/issues/243 ?

**Comment by lenowac** [comment]
> 
> 
> It worked for me to make a first account, but not to create a new one. I get "Invalid registration link, please contact your administrator". Maybe it is related to this [mattermost/focalboard#243](https://github.com/mattermost/focalboard/issues/243) ?

well I happen to know a fix to that, you need to generate one from the first account manually. Focalboard does not have open registration.

**Comment by lenowac** [comment]
Regarding this issue, I do not know how or what resolved it, but after nuking the install and doing a fresh one, it magically worked. 
Its still very buggy and to be frank, unusable, but installation and inital setup worked.

**Comment by TROMsite** [comment]
Focalboard does not have open registration. - oh I see....
